"""Initial migration

Revision ID: 423d928cb4f3
Revises: 
Create Date: 2024-03-13 20:47:47.759119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423d928cb4f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_badge_badge_name'), ['badge_name'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_badge_badge_name'), type_='unique')

    # ### end Alembic commands ###
