"""10

Revision ID: 70f812d9b3f6
Revises: ff77c5893155
Create Date: 2024-04-11 21:00:05.668148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f812d9b3f6'
down_revision = 'ff77c5893155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tickets_tags_tag_id_tags')),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('fk_tickets_tags_ticket_id_ticket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets_tags'))
    )
    op.drop_table('tickets__tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets__tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tickets_tags')
    # ### end Alembic commands ###
