"""Migration no. 2

Revision ID: a4d2d00c21f4
Revises: b16066c56f35
Create Date: 2024-03-15 14:18:18.924519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d2d00c21f4'
down_revision = 'b16066c56f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('tags_list', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_faq_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq'))
    )
    op.create_table('faq_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.String(length=100), nullable=True),
    sa.Column('attachment_location', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['faq_id'], ['faq.id'], name=op.f('fk_faq_attachment_faq_id_faq')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_attachment')
    op.drop_table('faq')
    # ### end Alembic commands ###
