"""Migration no. 1

Revision ID: c55d27dd43eb
Revises: 
Create Date: 2024-03-13 17:51:14.044662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55d27dd43eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assign_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('badge_name', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['badge_name'], ['badge.badge_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_badge')
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['badge_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('user_badge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('badge_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_by', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assign_badge')
    # ### end Alembic commands ###
